name       : nethogs
version    : 0.8.6
release    : 4
source     :
    - https://github.com/raboof/nethogs/archive/refs/tags/v0.8.6.tar.gz : 317c1d5235d4be677e494e931c41d063a783ac0ac51e35e345e621d261c2e5a0
license    : GPL-2.0-or-later
component  : network.util
summary    : NetHogs is a small net top tool
description: |
    NetHogs is a small net top tool
builddeps  :
    - pkgconfig(libpcap)
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
