name       : nethogs
version    : 0.8.5
release    : 1
source     :
    - https://github.com/raboof/nethogs/archive/v0.8.5.tar.gz : 6a9392726feca43228b3f0265379154946ef0544c2ca2cac59ec35a24f469dcc
license    : GPL-2.0
component  : network.util
summary    : NetHogs is a small net top tool
description: |
    NetHogs is a small net top tool
builddeps  :
    - libpcap-devel
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
